//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.31 at 03:44:03 PM BST 
//


package com.inm381.app.soacw.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="usan" type="{http://www.soacw.app.inm381.com/entity}Usan"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "usan"
})
@XmlRootElement(name = "getLappSRequest")
public class GetLappSRequest {

    @XmlElement(required = true)
    protected Usan usan;

    
    
    public GetLappSRequest() {

	}

	/**
     * Gets the value of the usan property.
     * 
     * @return
     *     possible object is
     *     {@link Usan }
     *     
     */
    public Usan getUsan() {
        return usan;
    }

    /**
     * Sets the value of the usan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Usan }
     *     
     */
    public void setUsan(Usan value) {
        this.usan = value;
    }

}
