//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.31 at 03:44:03 PM BST 
//


package com.inm381.app.soacw.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ArrayOfProperties" type="{http://www.soacw.app.inm381.com/entity}Property" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ArrayOfUroperties" type="{http://www.soacw.app.inm381.com/entity}Uroperty" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userID",
    "arrayOfProperties",
    "arrayOfUroperties"
})
@XmlRootElement(name = "getPstoSRequest")
public class GetPstoSRequest {

    protected long userID;
    @XmlElement(name = "ArrayOfProperties", nillable = true)
    protected List<Property> arrayOfProperties;
    @XmlElement(name = "ArrayOfUroperties", nillable = true)
    protected List<Uroperty> arrayOfUroperties;

    
    public GetPstoSRequest() {
		
	}

	/**
     * Gets the value of the userID property.
     * 
     */
    public long getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     */
    public void setUserID(long value) {
        this.userID = value;
    }

    /**
     * Gets the value of the arrayOfProperties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arrayOfProperties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArrayOfProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     * 
     * 
     */
    public List<Property> getArrayOfProperties() {
        if (arrayOfProperties == null) {
            arrayOfProperties = new ArrayList<Property>();
        }
        return this.arrayOfProperties;
    }

    /**
     * Gets the value of the arrayOfUroperties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arrayOfUroperties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArrayOfUroperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Uroperty }
     * 
     * 
     */
    public List<Uroperty> getArrayOfUroperties() {
        if (arrayOfUroperties == null) {
            arrayOfUroperties = new ArrayList<Uroperty>();
        }
        return this.arrayOfUroperties;
    }

}
