//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.31 at 03:44:03 PM BST 
//


package com.inm381.app.soacw.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pomsOffer" type="{http://www.soacw.app.inm381.com/entity}Offer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pomsOffer"
})
@XmlRootElement(name = "getPomSResponse")
public class GetPomSResponse {

    @XmlElement(required = true)
    protected Offer pomsOffer;

    /**
     * Gets the value of the pomsOffer property.
     * 
     * @return
     *     possible object is
     *     {@link Offer }
     *     
     */
    
    
    public Offer getPomsOffer() {
        return pomsOffer;
    }

    public GetPomSResponse() {
	
	}

	/**
     * Sets the value of the pomsOffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Offer }
     *     
     */
    public void setPomsOffer(Offer value) {
        this.pomsOffer = value;
    }

}
