//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.31 at 03:44:03 PM BST 
//


package com.inm381.app.soacw.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uroperty" type="{http://www.soacw.app.inm381.com/entity}Uroperty"/>
 *         &lt;element name="payment" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uroperty",
    "payment"
})
@XmlRootElement(name = "getPomSRequest")
public class GetPomSRequest {

    @XmlElement(required = true)
    protected Uroperty uroperty;
    protected double payment;

    
    
    public GetPomSRequest() {
	
	}

	/**
     * Gets the value of the uroperty property.
     * 
     * @return
     *     possible object is
     *     {@link Uroperty }
     *     
     */
    public Uroperty getUroperty() {
        return uroperty;
    }

    /**
     * Sets the value of the uroperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uroperty }
     *     
     */
    public void setUroperty(Uroperty value) {
        this.uroperty = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     */
    public double getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     */
    public void setPayment(double value) {
        this.payment = value;
    }

}
