//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.31 at 03:44:03 PM BST 
//


package com.inm381.app.soacw.entity;

import javax.xml.bind.annotation.XmlRegistry;

import com.inm381.app.soacw.domain.*;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.inm381.app.soacw.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.inm381.app.soacw.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetLappSRequest }
     * 
     */
    public GetLappSRequest createGetLappSRequest() {
        return new GetLappSRequest();
    }

    /**
     * Create an instance of {@link Usan }
     * 
     */
    public Usan createUsan() {
        return new Usan();
    }

    /**
     * Create an instance of {@link GetPserSRequest }
     * 
     */
    public GetPserSRequest createGetPserSRequest() {
        return new GetPserSRequest();
    }

    /**
     * Create an instance of {@link GetPstoSRequest }
     * 
     */
    public GetPstoSRequest createGetPstoSRequest() {
        return new GetPstoSRequest();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Uroperty }
     * 
     */
    public Uroperty createUroperty() {
        return new Uroperty();
    }

    /**
     * Create an instance of {@link GetLbroSResponse }
     * 
     */
    public GetLbroSResponse createGetLbroSResponse() {
        return new GetLbroSResponse();
    }

    /**
     * Create an instance of {@link Loan }
     * 
     */
    public Loan createLoan() {
        return new Loan();
    }

    /**
     * Create an instance of {@link GetPomSResponse }
     * 
     */
    public GetPomSResponse createGetPomSResponse() {
        return new GetPomSResponse();
    }

    /**
     * Create an instance of {@link Offer }
     * 
     */
    public Offer createOffer() {
        return new Offer();
    }

    /**
     * Create an instance of {@link GetCpaySResponse }
     * 
     */
    public GetCpaySResponse createGetCpaySResponse() {
        return new GetCpaySResponse();
    }

    /**
     * Create an instance of {@link GetPstoSResponse }
     * 
     */
    public GetPstoSResponse createGetPstoSResponse() {
        return new GetPstoSResponse();
    }

    /**
     * Create an instance of {@link GetPomSRequest }
     * 
     */
    public GetPomSRequest createGetPomSRequest() {
        return new GetPomSRequest();
    }

    /**
     * Create an instance of {@link GetCpaySRequest }
     * 
     */
    public GetCpaySRequest createGetCpaySRequest() {
        return new GetCpaySRequest();
    }

    /**
     * Create an instance of {@link LoanApplication }
     * 
     */
    public LoanApplication createLoanApplication() {
        return new LoanApplication();
    }

    /**
     * Create an instance of {@link GetLappSResponse }
     * 
     */
    public GetLappSResponse createGetLappSResponse() {
        return new GetLappSResponse();
    }

    /**
     * Create an instance of {@link GetPserSResponse }
     * 
     */
    public GetPserSResponse createGetPserSResponse() {
        return new GetPserSResponse();
    }

    /**
     * Create an instance of {@link GetLbroSRequest }
     * 
     */
    public GetLbroSRequest createGetLbroSRequest() {
        return new GetLbroSRequest();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link CardPayment }
     * 
     */
    public CardPayment createCardPayment() {
        return new CardPayment();
    }

}
