//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.31 at 03:44:03 PM BST 
//


package com.inm381.app.soacw.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Uroperty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Uroperty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="loanid" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="propertyid" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Uroperty", propOrder = {
    "id",
    "loanid",
    "propertyid"
})
public class Uroperty {

    protected long id;
    protected long loanid;
    protected long propertyid;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the loanid property.
     * 
     */
    public long getLoanid() {
        return loanid;
    }

    /**
     * Sets the value of the loanid property.
     * 
     */
    public void setLoanid(long value) {
        this.loanid = value;
    }

    /**
     * Gets the value of the propertyid property.
     * 
     */
    public long getPropertyid() {
        return propertyid;
    }

    /**
     * Sets the value of the propertyid property.
     * 
     */
    public void setPropertyid(long value) {
        this.propertyid = value;
    }

}
